name: Quality Check(Balocco way)
on:
  pull_request:
    types: [ synchronize, opened, reopened ]
    branches:
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
    paths:
      - '**.php'
      - '**.xml'
      - 'composer.json'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{secrets.COMPOSER_AUTH_PERSONAL_ACCESS_TOKEN}}"} }'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute quality check
        run: vendor/bin/balocco-qa run qc
